import os

from pyspark.sql import SparkSession

from config import DemoConfiguration

if __name__ == "__main__":
    spark_session = SparkSession.builder.master("local[*]").getOrCreate()

    spark_session.read.format('parquet').load(DemoConfiguration.OUTPUT_PATH).show(truncate=False)

    print('Files generated by Apache Spark')
    for device_file in os.listdir(path=DemoConfiguration.OUTPUT_PATH):
        print(f'File={device_file}')
