dataset:
  rows: 20
  composition_percentage:
    duplicates: 0
    missing_fields: 10
    unprocessable_rows: 0
data_blocker:
  type: sleep
  configuration:
    sleep_time_range_seconds:
      from: 30
      to: 60
entity:
  type: visit
  configuration:
    start_time: '2023-11-24T00:00:00Z'
generator:
  type: continuous
writer:
  type: postgresql
  configuration:
    host: 'postgresql'
    dbname: 'dedp'
    db_schema: 'dedp'
    user: 'dedp_test'
    password: 'dedp_test'
    table_name: 'visits_input'
    table_columns: ['visit_id', 'event_time', 'user_id', 'page', 'context']
    row_fields_to_insert: ['visit_id', 'event_time', 'user_id', 'page', 'context']