version: '3.1'
services:
  postgresql:
      image: postgres:15
      healthcheck:
        test: ['CMD', 'pg_isready', '-U postgres']
      container_name: dedp_postgresql
      environment:
        - POSTGRES_USER=dedp_test
        - POSTGRES_PASSWORD=dedp_test
        - POSTGRES_DB=dedp
      ports:
          - "5432:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  data_generator:
    image: 'waitingforcode/data-generator-blogging-platform:0.3-beta'
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - "/tmp/dedp/ch05/03-data-combination/01-distributed-json-postgresql/visits:/home/data_generator_user/data_generator_output"
      - "./generation_configuration.yaml:/home/data_generator_user/generation_configuration.yaml"
    entrypoint:
      - python3
      - /home/data_generator_user/data_generator/generate_dataset.py
      - --config_file
      - /home/data_generator_user/generation_configuration.yaml
