# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: definitons/invalid_visit.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'definitons/invalid_visit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from definitons import visit_pb2 as definitons_dot_visit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x64\x65\x66initons/invalid_visit.proto\x12\x12\x63om.waitingforcode\x1a\x16\x64\x65\x66initons/visit.proto\"A\n\x0fValidationError\x12\x14\n\x05\x66ield\x18\x01 \x01(\tR\x05\x66ield\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\"|\n\x0cInvalidVisit\x12/\n\x05visit\x18\x01 \x01(\x0b\x32\x19.com.waitingforcode.VisitR\x05visit\x12;\n\x06\x65rrors\x18\x02 \x03(\x0b\x32#.com.waitingforcode.ValidationErrorR\x06\x65rrorsB\x94\x01\n\x16\x63om.com.waitingforcodeB\x11InvalidVisitProtoP\x01\xa2\x02\x03\x43WX\xaa\x02\x12\x43om.Waitingforcode\xca\x02\x12\x43om\\Waitingforcode\xe2\x02\x1e\x43om\\Waitingforcode\\GPBMetadata\xea\x02\x13\x43om::Waitingforcodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'definitons.invalid_visit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.com.waitingforcodeB\021InvalidVisitProtoP\001\242\002\003CWX\252\002\022Com.Waitingforcode\312\002\022Com\\Waitingforcode\342\002\036Com\\Waitingforcode\\GPBMetadata\352\002\023Com::Waitingforcode'
  _globals['_VALIDATIONERROR']._serialized_start=78
  _globals['_VALIDATIONERROR']._serialized_end=143
  _globals['_INVALIDVISIT']._serialized_start=145
  _globals['_INVALIDVISIT']._serialized_end=269
# @@protoc_insertion_point(module_scope)
