# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: definitons/visit.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'definitons/visit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x65\x66initons/visit.proto\x12\x12\x63om.waitingforcode\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n\x05Visit\x12\"\n\x08visit_id\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x05R\x07visitId\x12\x46\n\nevent_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0b\xbaH\x08\xb2\x01\x02\x38\x01\xc8\x01\x01R\teventTime\x12\x1f\n\x07user_id\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06userId\x12\x65\n\x04page\x18\x04 \x01(\tBQ\xbaHN\xba\x01H\x12&Page cannot end with an html extension\x1a\x1ethis.endsWith(\'html\') == false\xc8\x01\x01R\x04pageB\x8d\x01\n\x16\x63om.com.waitingforcodeB\nVisitProtoP\x01\xa2\x02\x03\x43WX\xaa\x02\x12\x43om.Waitingforcode\xca\x02\x12\x43om\\Waitingforcode\xe2\x02\x1e\x43om\\Waitingforcode\\GPBMetadata\xea\x02\x13\x43om::Waitingforcodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'definitons.visit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.com.waitingforcodeB\nVisitProtoP\001\242\002\003CWX\252\002\022Com.Waitingforcode\312\002\022Com\\Waitingforcode\342\002\036Com\\Waitingforcode\\GPBMetadata\352\002\023Com::Waitingforcode'
  _globals['_VISIT'].fields_by_name['visit_id']._loaded_options = None
  _globals['_VISIT'].fields_by_name['visit_id']._serialized_options = b'\272H\004r\002\020\005'
  _globals['_VISIT'].fields_by_name['event_time']._loaded_options = None
  _globals['_VISIT'].fields_by_name['event_time']._serialized_options = b'\272H\010\262\001\0028\001\310\001\001'
  _globals['_VISIT'].fields_by_name['user_id']._loaded_options = None
  _globals['_VISIT'].fields_by_name['user_id']._serialized_options = b'\272H\003\310\001\001'
  _globals['_VISIT'].fields_by_name['page']._loaded_options = None
  _globals['_VISIT'].fields_by_name['page']._serialized_options = b'\272HN\272\001H\022&Page cannot end with an html extension\032\036this.endsWith(\'html\') == false\310\001\001'
  _globals['_VISIT']._serialized_start=109
  _globals['_VISIT']._serialized_end=360
# @@protoc_insertion_point(module_scope)
