---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "in-progress-{{ macros.uuid.uuid4() }}"
  namespace: dedp-ch03
spec:
  type: Scala
  mode: cluster
  image: "docker.io/library/dedp_ch03_backfilling_configurator:latest"
  imagePullPolicy: Never
  mainClass: com.waitingforcode.jobs.PartitionStateInProgressMarkerJob
  mainApplicationFile: "local:///tmp/backfilling_configurator-assembly-1.0.0-SNAPSHOT.jar"
  arguments:
    - '--outputLocationBaseDir'
    - "/data_for_demo/"
    - '--tableFullPath'
    - "/data_for_demo/devices"
    - '--outputFileName'
    - "current_partition_configuration_{{ ds }}.json"
    - '--partition'
    - "event_time={{ ds }}"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "datasets"
      hostPath:
        path: "/data_for_demo"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark-editor
    volumeMounts:
    - mountPath: "/data_for_demo"
      name: "datasets"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0
    volumeMounts:
    - mountPath: "/data_for_demo"
      name: "datasets"