reference_datasets:
  - reference_key: 'users_provider'
    entity:
      type: user
    dataset:
      rows: 5
    writer:
      type: postgresql
      configuration:
        host: 'postgresql'
        dbname: 'dedp'
        db_schema: 'dedp'
        user: 'dedp_test'
        password: 'dedp_test'
        table_name: 'users'
        table_columns: ['id', 'login', 'email', 'registered_datetime', 'first_connection_datetime', 'last_connection_datetime']
        row_fields_to_insert: ['id', 'login', 'email', 'registered_datetime', 'first_connection_datetime', 'last_connection_datetime']
dataset:
  rows: 500
data_blocker:
  type: 'no'
entity:
  type: visit
  configuration:
    start_time: '2023-11-24T00:00:00Z'
  reference_datasets:
    users: 'users_provider'
generator:
  type: one-shot
writer:
  type: postgresql
  configuration:
    host: 'postgresql'
    dbname: 'dedp'
    db_schema: 'dedp'
    user: 'dedp_test'
    password: 'dedp_test'
    table_name: 'visits'
    table_columns: ['visit_id', 'event_time', 'user_id', 'page', 'context']
    row_fields_to_insert: ['visit_id', 'event_time', 'user_id', 'page', 'context']
