version: '3.1'
services:
  web:
    image: marquezproject/marquez-web:0.49.0
    container_name: marquez-web
    environment:
      - MARQUEZ_HOST=marquez_api
      - MARQUEZ_PORT=5000
    ports:
      - 3000:3000
  marquez_api:
    image: marquezproject/marquez:0.49.0
    container_name: marquez-api
    ports:
      - "5000:5000"
      - "5001:5001"
    links:
      - "marquez_db:postgres"
    depends_on:
      marquez_db:
        condition: service_healthy
  marquez_db:
    image: postgres:15
    container_name: marquez-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "marquez"]
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
      - POSTGRES_DB=marquez