dataset:
  rows: 500
data_blocker:
  type: 'no'
entity:
  type: visit
  configuration:
    start_time: '2023-11-24T00:00:00Z'
generator:
  type: one-shot
writer:
  type: json
  configuration:
    output_path: '/home/data_generator_user/data_generator_output/input'
    clean_path: true
  partitions: ['partition1', 'partition2']