version: '3.1'
services:
  data_generator:
    image: waitingforcode/data-generator-blogging-platform:0.2-beta
    volumes:
      - /tmp/dedp/ch03/late-data-integrator/dataset:/home/data_generator_user/data_generator_output
      - ./generation_configuration_json.yaml:/home/data_generator_user/generation_configuration_json.yaml
    entrypoint:
      - python3
      - /home/data_generator_user/data_generator/generate_dataset.py
      - --config_file
      - /home/data_generator_user/generation_configuration_json.yaml
