version: '3.1'
services:
  kafka:
    image: 'bitnami/kafka:3.5'
    container_name: passthrough_replicator_kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_DELETE_TOPIC_ENABLE=true
  data_generator:
    image: waitingforcode/data-generator-blogging-platform:0.1-beta
    container_name: data_generator_passthrough_replicator
    volumes:
      - /tmp/dedp/ch02/replication/passthrough-replicator:/home/data_generator_user/data_generator_output
      - ./generation_configuration_json.yaml:/home/data_generator_user/generation_configuration_json.yaml
    entrypoint:
      - python3
      - /home/data_generator_user/data_generator/generate_dataset.py
      - --config_file
      - /home/data_generator_user/generation_configuration_json.yaml
