version: '3'
services:
  data_generator:
    image: 'waitingforcode/data-generator-blogging-platform:0.1-beta'
    volumes:
      - "/tmp/dedp/ch08/03-access-optimization/01-metadata-enhancer-delta-lake/input/:/home/data_generator_user/data_generator_output"
      - "./generation_configuration.yaml:/home/data_generator_user/generation_configuration.yaml"
    entrypoint:
      - python3
      - /home/data_generator_user/data_generator/generate_dataset.py
      - --config_file
      - /home/data_generator_user/generation_configuration.yaml
